server:
  port: 8083
auth0:
  audience: https://hotel-microservices-api
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope: openid, profile, email, offline_access
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8083/login/oauth2/code/auth0"
        provider:
          auth0:
            issuer-uri: https://dev-inejhxufj1vndb4r.uk.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://dev-inejhxufj1vndb4r.uk.auth0.com/

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - TokenRelay=
          
            - id: hotel-service
              uri: lb://HOTEL-SERVICE
              predicates:
                - Path=/hotels/**
              filters:
                - TokenRelay=
              
            - id: rating-service
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/ratings/**
              filters:
                - TokenRelay=
