server:
  port: 8083

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: hotel-service
              uri: lb://HOTEL-SERVICE
              predicates:
                - Path=/hotels/**

            - id: rating-service
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/ratings/**
